### ISSUE TITLE
Could not find package consult-selectrum 

### ISSUE THREAD

**Issue by kixi** [lambdaisland/corgi#6]
When I do a fresh install using the same init.el you provided on the documentation page, I get the error:

error: Could not find package consult-selectrum in recipe repositories: (corgi-packages org-elpa melpa gnu-elpa-mirror emacsmirror-mirror)

**Comment by plexus** [comment]
Hi @kixi , I've pushed my latest version of corgi-packages. Note that this project is very much pre-alpha, so don't expect any "how to" kind of support here. People who want to get involved at this point have to be willing and able to get there hands dirty to track down and help fix any issues that arise.

**Comment by kixi** [comment]
Hi @plexus , thanks! I used your Emacs configuration before and I very much liked it, so I wanted to try out the new package based version. So looks like I have to finally start learning Emacs Lisp ;)

**Comment by plexus** [comment]
We briefly used selectrum but then removed it again, I'm guessing you ended up trying Corgi at an unfortunate time where there was still a lingering reference somewhere causing problems. Things have continued to get better in the past year, so feel free to give it another go!
